//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tracktor.app
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TContextDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TContextDto : object
    {
        
        private int TUserIDField;
        
        private int UTCOffsetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TUserID
        {
            get
            {
                return this.TUserIDField;
            }
            set
            {
                this.TUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UTCOffset
        {
            get
            {
                return this.UTCOffsetField;
            }
            set
            {
                this.UTCOffsetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSummaryModelDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TSummaryModelDto : object
    {
        
        private bool InProgressField;
        
        private tracktor.app.TProjectDto[] ProjectsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InProgress
        {
            get
            {
                return this.InProgressField;
            }
            set
            {
                this.InProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TProjectDto[] Projects
        {
            get
            {
                return this.ProjectsField;
            }
            set
            {
                this.ProjectsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TProjectDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TProjectDto : object
    {
        
        private int DisplayOrderField;
        
        private bool InProgressField;
        
        private bool IsObsoleteField;
        
        private string NameField;
        
        private int TProjectIDField;
        
        private tracktor.app.TTaskDto[] TTasksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder
        {
            get
            {
                return this.DisplayOrderField;
            }
            set
            {
                this.DisplayOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InProgress
        {
            get
            {
                return this.InProgressField;
            }
            set
            {
                this.InProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsObsolete
        {
            get
            {
                return this.IsObsoleteField;
            }
            set
            {
                this.IsObsoleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TProjectID
        {
            get
            {
                return this.TProjectIDField;
            }
            set
            {
                this.TProjectIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TTaskDto[] TTasks
        {
            get
            {
                return this.TTasksField;
            }
            set
            {
                this.TTasksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TTaskDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TTaskDto : object
    {
        
        private tracktor.app.TContribDto ContribField;
        
        private int DisplayOrderField;
        
        private bool InProgressField;
        
        private bool IsObsoleteField;
        
        private string NameField;
        
        private int TProjectIDField;
        
        private int TTaskIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TContribDto Contrib
        {
            get
            {
                return this.ContribField;
            }
            set
            {
                this.ContribField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder
        {
            get
            {
                return this.DisplayOrderField;
            }
            set
            {
                this.DisplayOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InProgress
        {
            get
            {
                return this.InProgressField;
            }
            set
            {
                this.InProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsObsolete
        {
            get
            {
                return this.IsObsoleteField;
            }
            set
            {
                this.IsObsoleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TProjectID
        {
            get
            {
                return this.TProjectIDField;
            }
            set
            {
                this.TProjectIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TTaskID
        {
            get
            {
                return this.TTaskIDField;
            }
            set
            {
                this.TTaskIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TContribDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial struct TContribDto
    {
        
        private double ThisMonthField;
        
        private double ThisWeekField;
        
        private double TodayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ThisMonth
        {
            get
            {
                return this.ThisMonthField;
            }
            set
            {
                this.ThisMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ThisWeek
        {
            get
            {
                return this.ThisWeekField;
            }
            set
            {
                this.ThisWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Today
        {
            get
            {
                return this.TodayField;
            }
            set
            {
                this.TodayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TStatusModelDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TStatusModelDto : object
    {
        
        private bool InProgressField;
        
        private tracktor.app.TEntryDto LatestEntryField;
        
        private tracktor.app.TTaskDto TTaskInProgressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InProgress
        {
            get
            {
                return this.InProgressField;
            }
            set
            {
                this.InProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TEntryDto LatestEntry
        {
            get
            {
                return this.LatestEntryField;
            }
            set
            {
                this.LatestEntryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TTaskDto TTaskInProgress
        {
            get
            {
                return this.TTaskInProgressField;
            }
            set
            {
                this.TTaskInProgressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TEntryDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TEntryDto : object
    {
        
        private double ContribField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private bool InProgressField;
        
        private bool IsDeletedField;
        
        private string ProjectNameField;
        
        private System.DateTime StartDateField;
        
        private int TEntryIDField;
        
        private int TTaskIDField;
        
        private string TaskNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Contrib
        {
            get
            {
                return this.ContribField;
            }
            set
            {
                this.ContribField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InProgress
        {
            get
            {
                return this.InProgressField;
            }
            set
            {
                this.InProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TEntryID
        {
            get
            {
                return this.TEntryIDField;
            }
            set
            {
                this.TEntryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TTaskID
        {
            get
            {
                return this.TTaskIDField;
            }
            set
            {
                this.TTaskIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName
        {
            get
            {
                return this.TaskNameField;
            }
            set
            {
                this.TaskNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TEntriesModelDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TEntriesModelDto : object
    {
        
        private tracktor.app.TEntryDto[] EntriesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tracktor.app.TEntryDto[] Entries
        {
            get
            {
                return this.EntriesField;
            }
            set
            {
                this.EntriesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TReportModelDto", Namespace="http://schemas.datacontract.org/2004/07/tracktor.service")]
    public partial class TReportModelDto : object
    {
        
        private System.Collections.Generic.Dictionary<System.DateTime, double> DayContribsField;
        
        private System.Collections.Generic.Dictionary<int, double> TaskContribsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<System.DateTime, double> DayContribs
        {
            get
            {
                return this.DayContribsField;
            }
            set
            {
                this.DayContribsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, double> TaskContribs
        {
            get
            {
                return this.TaskContribsField;
            }
            set
            {
                this.TaskContribsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tracktor.app.ITracktorService")]
    public interface ITracktorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/CreateUser", ReplyAction="http://tempuri.org/ITracktorService/CreateUserResponse")]
        System.Threading.Tasks.Task<int> CreateUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/GetSummaryModel", ReplyAction="http://tempuri.org/ITracktorService/GetSummaryModelResponse")]
        System.Threading.Tasks.Task<tracktor.app.TSummaryModelDto> GetSummaryModelAsync(tracktor.app.TContextDto context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/GetStatusModel", ReplyAction="http://tempuri.org/ITracktorService/GetStatusModelResponse")]
        System.Threading.Tasks.Task<tracktor.app.TStatusModelDto> GetStatusModelAsync(tracktor.app.TContextDto context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/GetEntriesModel", ReplyAction="http://tempuri.org/ITracktorService/GetEntriesModelResponse")]
        System.Threading.Tasks.Task<tracktor.app.TEntriesModelDto> GetEntriesModelAsync(tracktor.app.TContextDto context, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, int projectID, int startNo, int maxEntries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/GetReportModel", ReplyAction="http://tempuri.org/ITracktorService/GetReportModelResponse")]
        System.Threading.Tasks.Task<tracktor.app.TReportModelDto> GetReportModelAsync(tracktor.app.TContextDto context, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, int projectID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/UpdateTask", ReplyAction="http://tempuri.org/ITracktorService/UpdateTaskResponse")]
        System.Threading.Tasks.Task<tracktor.app.TTaskDto> UpdateTaskAsync(tracktor.app.TContextDto context, tracktor.app.TTaskDto task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/UpdateProject", ReplyAction="http://tempuri.org/ITracktorService/UpdateProjectResponse")]
        System.Threading.Tasks.Task<tracktor.app.TProjectDto> UpdateProjectAsync(tracktor.app.TContextDto context, tracktor.app.TProjectDto project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/GetEntry", ReplyAction="http://tempuri.org/ITracktorService/GetEntryResponse")]
        System.Threading.Tasks.Task<tracktor.app.TEntryDto> GetEntryAsync(tracktor.app.TContextDto context, int entryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/UpdateEntry", ReplyAction="http://tempuri.org/ITracktorService/UpdateEntryResponse")]
        System.Threading.Tasks.Task<tracktor.app.TEntryDto> UpdateEntryAsync(tracktor.app.TContextDto context, tracktor.app.TEntryDto entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/StopTask", ReplyAction="http://tempuri.org/ITracktorService/StopTaskResponse")]
        System.Threading.Tasks.Task StopTaskAsync(tracktor.app.TContextDto context, int currentTaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/StartTask", ReplyAction="http://tempuri.org/ITracktorService/StartTaskResponse")]
        System.Threading.Tasks.Task StartTaskAsync(tracktor.app.TContextDto context, int newTaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITracktorService/SwitchTask", ReplyAction="http://tempuri.org/ITracktorService/SwitchTaskResponse")]
        System.Threading.Tasks.Task SwitchTaskAsync(tracktor.app.TContextDto context, int currentTaskID, int newTaskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface ITracktorServiceChannel : tracktor.app.ITracktorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class TracktorServiceClient : System.ServiceModel.ClientBase<tracktor.app.ITracktorService>, tracktor.app.ITracktorService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TracktorServiceClient() : 
                base(TracktorServiceClient.GetDefaultBinding(), TracktorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITracktorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracktorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TracktorServiceClient.GetBindingForEndpoint(endpointConfiguration), TracktorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracktorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TracktorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracktorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TracktorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TracktorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> CreateUserAsync(string userName)
        {
            return base.Channel.CreateUserAsync(userName);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TSummaryModelDto> GetSummaryModelAsync(tracktor.app.TContextDto context)
        {
            return base.Channel.GetSummaryModelAsync(context);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TStatusModelDto> GetStatusModelAsync(tracktor.app.TContextDto context)
        {
            return base.Channel.GetStatusModelAsync(context);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TEntriesModelDto> GetEntriesModelAsync(tracktor.app.TContextDto context, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, int projectID, int startNo, int maxEntries)
        {
            return base.Channel.GetEntriesModelAsync(context, startDate, endDate, projectID, startNo, maxEntries);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TReportModelDto> GetReportModelAsync(tracktor.app.TContextDto context, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, int projectID, int taskID)
        {
            return base.Channel.GetReportModelAsync(context, startDate, endDate, projectID, taskID);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TTaskDto> UpdateTaskAsync(tracktor.app.TContextDto context, tracktor.app.TTaskDto task)
        {
            return base.Channel.UpdateTaskAsync(context, task);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TProjectDto> UpdateProjectAsync(tracktor.app.TContextDto context, tracktor.app.TProjectDto project)
        {
            return base.Channel.UpdateProjectAsync(context, project);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TEntryDto> GetEntryAsync(tracktor.app.TContextDto context, int entryID)
        {
            return base.Channel.GetEntryAsync(context, entryID);
        }
        
        public System.Threading.Tasks.Task<tracktor.app.TEntryDto> UpdateEntryAsync(tracktor.app.TContextDto context, tracktor.app.TEntryDto entry)
        {
            return base.Channel.UpdateEntryAsync(context, entry);
        }
        
        public System.Threading.Tasks.Task StopTaskAsync(tracktor.app.TContextDto context, int currentTaskID)
        {
            return base.Channel.StopTaskAsync(context, currentTaskID);
        }
        
        public System.Threading.Tasks.Task StartTaskAsync(tracktor.app.TContextDto context, int newTaskID)
        {
            return base.Channel.StartTaskAsync(context, newTaskID);
        }
        
        public System.Threading.Tasks.Task SwitchTaskAsync(tracktor.app.TContextDto context, int currentTaskID, int newTaskId)
        {
            return base.Channel.SwitchTaskAsync(context, currentTaskID, newTaskId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITracktorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITracktorService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:38744/TracktorService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TracktorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITracktorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TracktorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITracktorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITracktorService,
        }
    }
}
